<?php

include 'onther page/header.php';

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" href="img/logo.png" type="image/x-icon">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/navbar.css">      
        <!-- ===== CSS ===== -->
    <title>Neptune</title>
</head>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Madimi+One&family=Ojuju:wght@200..800&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap');

*{
    font-family: "Rubik", sans-serif;
 margin: 0;
 padding: 0;
 box-sizing: border-box;  
 scroll-behavior: smooth;
}

/*start*/

.contaner{
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    flex-direction: row;
    flex-wrap: wrap;
}
.vid{
        background-repeat: no-repeat;
background-size: cover;
width: 107.5%;
margin: 0;
    padding: 0;
    /* position: fixed; */


    }
    body::-webkit-scrollbar{
    display: none;
}
.info{
    /* margin-top: 40% !important; */
   color: #fff;
   position: fixed;
   text-align: left;

}
.info img{
    width: 85%;
    margin-top: 90px;
    margin-left: -90px;


}
.info .lol{
 height: 330px !important;
    width: 562px !important;
    margin-top: -33% !important;
    margin-left: 16% !important;
}}
</style>
<body>
<div class="contaner">
<!-- <video  src="vid/backgroung.mp4" autoplay loop></video> -->
<video  autoplay lood muted class="vid">
    <source  src="vid/Neptune.mp4" type="video/mp4">
</video>
<div class="info">
    <div >
<img src="img/inf.png" alt="" srcset="">
<div class="lol" style="height:160px;width:300px;font:20px/30px Georgia, Garamond, Serif;overflow:auto;">
Neptune: The Distant Blue Giant
Neptune is the eighth and most distant planet from the Sun in our solar system. It's a gas giant, often categorized as an ice giant due to its composition of elements like hydrogen, helium, methane, and water ice.   

Key Facts About Neptune:
*Color: Neptune is known for its deep blue color, attributed to the methane in its atmosphere, which absorbs red light and reflects blue light.   
*Size: Neptune is the third-largest planet in our solar system, with a diameter about four times that of Earth.
*Distance: Neptune orbits the Sun at an average distance of about 2.8 billion miles (4.5 billion kilometers).   
*Temperature: Neptune is one of the coldest places in the solar system, with temperatures at its cloud tops reaching as low as -218 degrees Celsius (-361 degrees Fahrenheit).   
*Moons: Neptune has 14 known moons, the most prominent of which is Triton.
*Rings: Neptune has a faint system of rings, discovered in 1989 by the Voyager 2 spacecraft.   
*Great Dark Spot: This is a large storm system on Neptune, similar to Jupiter's Great Red Spot.   
*Magnetic Field: Neptune has a strong magnetic field, which is likely generated by the movement of conductive fluids within its interior.                                            diameter of about 12,742 km and a mass of approximately 5.97 × 10^24 kg. Earth orbits the Sun 
                                            at an average distance of 149.6 million km, completing one revolution in 365.26 days. It has one 
                                            natural satellite, the Moon, and a diverse atmosphere primarily composed of nitrogen and oxygen. 
</dive>
</div>

</div>
   
</div>
</body>
</html>